.global gKaoChikorita
gKaoChikorita:
kao_siro sPortraitsChikorita
sChikoritaNormalPal:
.incbin "baserom.gba", 0x169E534, 0x40
.global sChikoritaNormalGfx
sChikoritaNormalGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x169E579, 0x29F
sChikoritaHappyPal:
.incbin "baserom.gba", 0x169E818, 0x40
.global sChikoritaHappyGfx
sChikoritaHappyGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x169E85D, 0x27F
sChikoritaPainedPal:
.incbin "baserom.gba", 0x169EADC, 0x40
.global sChikoritaPainedGfx
sChikoritaPainedGfx:
.incbin "baserom.gba", 0x169EB1C, 0x290
sChikoritaAngryPal:
.incbin "baserom.gba", 0x169EDAC, 0x40
.global sChikoritaAngryGfx
sChikoritaAngryGfx:
.incbin "baserom.gba", 0x169EDEC, 0x27C
sChikoritaWorriedPal:
.incbin "baserom.gba", 0x169F068, 0x40
.global sChikoritaWorriedGfx
sChikoritaWorriedGfx:
.incbin "baserom.gba", 0x169F0A8, 0x294
sChikoritaSadPal:
.incbin "baserom.gba", 0x169F33C, 0x40
.global sChikoritaSadGfx
sChikoritaSadGfx:
.incbin "baserom.gba", 0x169F37C, 0x2A0
sChikoritaCryingPal:
.incbin "baserom.gba", 0x169F61C, 0x40
.global sChikoritaCryingGfx
sChikoritaCryingGfx:
.incbin "baserom.gba", 0x169F65C, 0x2A8
sChikoritaShoutingPal:
.incbin "baserom.gba", 0x169F904, 0x40
.global sChikoritaShoutingGfx
sChikoritaShoutingGfx:
.incbin "baserom.gba", 0x169F944, 0x290
sChikoritaTearyEyePal:
.incbin "baserom.gba", 0x169FBD4, 0x40
.global sChikoritaTearyEyeGfx
sChikoritaTearyEyeGfx:
.incbin "baserom.gba", 0x169FC14, 0x2A4
sChikoritaDeterminedPal:
.incbin "baserom.gba", 0x169FEB8, 0x40
.global sChikoritaDeterminedGfx
sChikoritaDeterminedGfx:
.incbin "baserom.gba", 0x169FEF8, 0x270
sChikoritaJoyousPal:
.incbin "baserom.gba", 0x16A0168, 0x40
.global sChikoritaJoyousGfx
sChikoritaJoyousGfx:
.incbin "baserom.gba", 0x16A01A8, 0x2C0
sChikoritaInspiredPal:
.incbin "baserom.gba", 0x16A0468, 0x40
.global sChikoritaInspiredGfx
sChikoritaInspiredGfx:
.incbin "baserom.gba", 0x16A04A8, 0x29C
sChikoritaSurprisedPal:
.incbin "baserom.gba", 0x16A0744, 0x40
.global sChikoritaSurprisedGfx
sChikoritaSurprisedGfx:
.incbin "baserom.gba", 0x16A0784, 0x2AC
sPortraitsChikorita:
kao_portrait sChikoritaNormalPal, sChikoritaNormalGfx
kao_portrait sChikoritaHappyPal, sChikoritaHappyGfx
kao_portrait sChikoritaPainedPal, sChikoritaPainedGfx
kao_portrait sChikoritaAngryPal, sChikoritaAngryGfx
kao_portrait sChikoritaWorriedPal, sChikoritaWorriedGfx
kao_portrait sChikoritaSadPal, sChikoritaSadGfx
kao_portrait sChikoritaCryingPal, sChikoritaCryingGfx
kao_portrait sChikoritaShoutingPal, sChikoritaShoutingGfx
kao_portrait sChikoritaTearyEyePal, sChikoritaTearyEyeGfx
kao_portrait sChikoritaDeterminedPal, sChikoritaDeterminedGfx
kao_portrait sChikoritaJoyousPal, sChikoritaJoyousGfx
kao_portrait sChikoritaInspiredPal, sChikoritaInspiredGfx
kao_portrait sChikoritaSurprisedPal, sChikoritaSurprisedGfx
