.global gKaoTorchic
gKaoTorchic:
kao_siro sPortraitsTorchic
sTorchicNormalPal:
.incbin "baserom.gba", 0x16ABC24, 0x40
.global sTorchicNormalGfx
sTorchicNormalGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x16ABC69, 0x287
sTorchicHappyPal:
.incbin "baserom.gba", 0x16ABEF0, 0x40
.global sTorchicHappyGfx
sTorchicHappyGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x16ABF35, 0x2A3
sTorchicPainedPal:
.incbin "baserom.gba", 0x16AC1D8, 0x40
.global sTorchicPainedGfx
sTorchicPainedGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x16AC21D, 0x2B3
sTorchicAngryPal:
.incbin "baserom.gba", 0x16AC4D0, 0x40
.global sTorchicAngryGfx
sTorchicAngryGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x16AC515, 0x293
sTorchicWorriedPal:
.incbin "baserom.gba", 0x16AC7A8, 0x40
.global sTorchicWorriedGfx
sTorchicWorriedGfx:
.incbin "baserom.gba", 0x16AC7E8, 0x260
sTorchicSadPal:
.incbin "baserom.gba", 0x16ACA48, 0x40
.global sTorchicSadGfx
sTorchicSadGfx:
.incbin "baserom.gba", 0x16ACA88, 0x290
sTorchicCryingPal:
.incbin "baserom.gba", 0x16ACD18, 0x40
.global sTorchicCryingGfx
sTorchicCryingGfx:
.incbin "baserom.gba", 0x16ACD58, 0x28C
sTorchicShoutingPal:
.incbin "baserom.gba", 0x16ACFE4, 0x40
.global sTorchicShoutingGfx
sTorchicShoutingGfx:
.incbin "baserom.gba", 0x16AD024, 0x2D4
sTorchicTearyEyePal:
.incbin "baserom.gba", 0x16AD2F8, 0x40
.global sTorchicTearyEyeGfx
sTorchicTearyEyeGfx:
.incbin "baserom.gba", 0x16AD338, 0x29C
sTorchicDeterminedPal:
.incbin "baserom.gba", 0x16AD5D4, 0x40
.global sTorchicDeterminedGfx
sTorchicDeterminedGfx:
.incbin "baserom.gba", 0x16AD614, 0x29C
sTorchicJoyousPal:
.incbin "baserom.gba", 0x16AD8B0, 0x40
.global sTorchicJoyousGfx
sTorchicJoyousGfx:
.string "AT4PX"
.incbin "baserom.gba", 0x16AD8F5, 0x29F
sTorchicInspiredPal:
.incbin "baserom.gba", 0x16ADB94, 0x40
.global sTorchicInspiredGfx
sTorchicInspiredGfx:
.incbin "baserom.gba", 0x16ADBD4, 0x288
sTorchicSurprisedPal:
.incbin "baserom.gba", 0x16ADE5C, 0x40
.global sTorchicSurprisedGfx
sTorchicSurprisedGfx:
.incbin "baserom.gba", 0x16ADE9C, 0x2C0
sPortraitsTorchic:
kao_portrait sTorchicNormalPal, sTorchicNormalGfx
kao_portrait sTorchicHappyPal, sTorchicHappyGfx
kao_portrait sTorchicPainedPal, sTorchicPainedGfx
kao_portrait sTorchicAngryPal, sTorchicAngryGfx
kao_portrait sTorchicWorriedPal, sTorchicWorriedGfx
kao_portrait sTorchicSadPal, sTorchicSadGfx
kao_portrait sTorchicCryingPal, sTorchicCryingGfx
kao_portrait sTorchicShoutingPal, sTorchicShoutingGfx
kao_portrait sTorchicTearyEyePal, sTorchicTearyEyeGfx
kao_portrait sTorchicDeterminedPal, sTorchicDeterminedGfx
kao_portrait sTorchicJoyousPal, sTorchicJoyousGfx
kao_portrait sTorchicInspiredPal, sTorchicInspiredGfx
kao_portrait sTorchicSurprisedPal, sTorchicSurprisedGfx
