/* Auto-generated by tools/gen_spritecollab_runtime_portraits.py. Do not edit by hand. */
#ifndef GUARD_GENERATED_KAO_TABLE_H
#define GUARD_GENERATED_KAO_TABLE_H

#include "global.h"
#include "constants/monster.h"

extern const u8 *const gGeneratedKaoPortraitData[MONSTER_MAX];
extern const u8 *const gGeneratedKaoShinyPortraitData[MONSTER_MAX];

#endif /* GUARD_GENERATED_KAO_TABLE_H */
