/* Auto-generated by tools/gen_spritecollab_runtime_portraits_full_expr.py.
 * Do not edit by hand.
 */
#ifndef GUARD_GENERATED_KAO_TABLE_H
#define GUARD_GENERATED_KAO_TABLE_H

#include "global.h"
#include "constants/monster.h"

extern const u8 *const gGeneratedKaoPortraitData[MONSTER_MAX];
extern const u8 *const gGeneratedKaoShinyPortraitData[MONSTER_MAX];


/* Generated normal replacement portraits for reclaimed base KAO files. */
extern const u8 gPortraitsRuntimeGenerated359ABSOL[];
extern const u8 gPortraitsRuntimeGenerated065ALAKAZAM[];
extern const u8 gPortraitsRuntimeGenerated144ARTICUNO[];
extern const u8 gPortraitsRuntimeGenerated069BELLSPROUT[];
extern const u8 gPortraitsRuntimeGenerated009BLASTOISE[];
extern const u8 gPortraitsRuntimeGenerated001BULBASAUR[];
extern const u8 gPortraitsRuntimeGenerated012BUTTERFREE[];
extern const u8 gPortraitsRuntimeGenerated010CATERPIE[];
extern const u8 gPortraitsRuntimeGenerated006CHARIZARD[];
extern const u8 gPortraitsRuntimeGenerated004CHARMANDER[];
extern const u8 gPortraitsRuntimeGenerated152CHIKORITA[];
extern const u8 gPortraitsRuntimeGenerated104CUBONE[];
extern const u8 gPortraitsRuntimeGenerated155CYNDAQUIL[];
extern const u8 gPortraitsRuntimeGenerated050DIGLETT[];
extern const u8 gPortraitsRuntimeGenerated051DUGTRIO[];
extern const u8 gPortraitsRuntimeGenerated133EEVEE[];
extern const u8 gPortraitsRuntimeGenerated023EKANS[];
extern const u8 gPortraitsRuntimeGenerated244ENTEI[];
extern const u8 gPortraitsRuntimeGenerated282GARDEVOIR[];
extern const u8 gPortraitsRuntimeGenerated094GENGAR[];
extern const u8 gPortraitsRuntimeGenerated076GOLEM[];
extern const u8 gPortraitsRuntimeGenerated210GRANBULL[];
extern const u8 gPortraitsRuntimeGenerated383GROUDON[];
extern const u8 gPortraitsRuntimeGenerated316GULPIN[];
extern const u8 gPortraitsRuntimeGenerated250HO_OH[];
extern const u8 gPortraitsRuntimeGenerated385JIRACHI[];
extern const u8 gPortraitsRuntimeGenerated189JUMPLUFF[];
extern const u8 gPortraitsRuntimeGenerated115KANGASKHAN[];
extern const u8 gPortraitsRuntimeGenerated352KECLEON[];
extern const u8 gPortraitsRuntimeGenerated382KYOGRE[];
extern const u8 gPortraitsRuntimeGenerated380LATIAS[];
extern const u8 gPortraitsRuntimeGenerated381LATIOS[];
extern const u8 gPortraitsRuntimeGenerated271LOMBRE[];
extern const u8 gPortraitsRuntimeGenerated249LUGIA[];
extern const u8 gPortraitsRuntimeGenerated066MACHOP[];
extern const u8 gPortraitsRuntimeGenerated081MAGNEMITE[];
extern const u8 gPortraitsRuntimeGenerated296MAKUHITA[];
extern const u8 gPortraitsRuntimeGenerated308MEDICHAM[];
extern const u8 gPortraitsRuntimeGenerated052MEOWTH[];
extern const u8 gPortraitsRuntimeGenerated011METAPOD[];
extern const u8 gPortraitsRuntimeGenerated150MEWTWO[];
extern const u8 gPortraitsRuntimeGenerated146MOLTRES[];
extern const u8 gPortraitsRuntimeGenerated258MUDKIP[];
extern const u8 gPortraitsRuntimeGenerated038NINETALES[];
extern const u8 gPortraitsRuntimeGenerated224OCTILLERY[];
extern const u8 gPortraitsRuntimeGenerated279PELIPPER[];
extern const u8 gPortraitsRuntimeGenerated053PERSIAN[];
extern const u8 gPortraitsRuntimeGenerated025PIKACHU[];
extern const u8 gPortraitsRuntimeGenerated054PSYDUCK[];
extern const u8 gPortraitsRuntimeGenerated243RAIKOU[];
extern const u8 gPortraitsRuntimeGenerated384RAYQUAZA[];
extern const u8 gPortraitsRuntimeGenerated275SHIFTRY[];
extern const u8 gPortraitsRuntimeGenerated227SKARMORY[];
extern const u8 gPortraitsRuntimeGenerated300SKITTY[];
extern const u8 gPortraitsRuntimeGenerated235SMEARGLE[];
extern const u8 gPortraitsRuntimeGenerated209SNUBBULL[];
extern const u8 gPortraitsRuntimeGenerated327SPINDA[];
extern const u8 gPortraitsRuntimeGenerated007SQUIRTLE[];
extern const u8 gPortraitsRuntimeGenerated245SUICUNE[];
extern const u8 gPortraitsRuntimeGenerated255TORCHIC[];
extern const u8 gPortraitsRuntimeGenerated158TOTODILE[];
extern const u8 gPortraitsRuntimeGenerated252TREECKO[];
extern const u8 gPortraitsRuntimeGenerated248TYRANITAR[];
extern const u8 gPortraitsRuntimeGenerated340WHISCASH[];
extern const u8 gPortraitsRuntimeGenerated040WIGGLYTUFF[];
extern const u8 gPortraitsRuntimeGenerated202WOBBUFFET[];
extern const u8 gPortraitsRuntimeGenerated360WYNAUT[];
extern const u8 gPortraitsRuntimeGenerated178XATU[];
extern const u8 gPortraitsRuntimeGenerated145ZAPDOS[];

#endif /* GUARD_GENERATED_KAO_TABLE_H */
