/* Auto-generated by tools/gen_spritecollab_portraits.py. Do not edit by hand. */
#ifndef GUARD_GENERATED_PORTRAIT_TABLE_H
#define GUARD_GENERATED_PORTRAIT_TABLE_H

#include "global.h"
#include "constants/monster.h"

extern const u32 gGeneratedPortraitBits[MONSTER_MAX];
extern const u32 gGeneratedShinyPortraitBits[MONSTER_MAX];

#endif /* GUARD_GENERATED_PORTRAIT_TABLE_H */
